### ISSUE TITLE
adding example CSV via https not working 

### ISSUE THREAD

**Issue by ericknudson** [Markenson/csv-metabase-driver#22]
1. I used the settings here: https://github.com/Markenson/csv-metabase-driver/releases/tag/1.1.0. 
<img width="1436" alt="Screen Shot 2021-06-11 at 9 56 36 AM" src="https://user-images.githubusercontent.com/25067227/121697713-50d7e580-ca9b-11eb-90a3-a8735e702984.png">
2. After import, I only see only one table that's misnamed:
<img width="496" alt="Screen Shot 2021-06-11 at 9 57 15 AM" src="https://user-images.githubusercontent.com/25067227/121697798-677e3c80-ca9b-11eb-993b-b96be0f94072.png">
3. And clicking into that table gives me the following syntax error:
`Syntax error: Encountered " <NAME> "\"id\" "" at line 2, column 27. Was expecting: <EOF>`

Any suggestions for how to troubleshoot this?

**Comment by Markenson** [comment]
Hi everyone! 
Sorry... My time is tight, but I will try to look into this issue if possible.

**Comment by Markenson** [comment]
Hi @ericknudson !

I this that problem was related to issue https://github.com/Markenson/csv-metabase-driver/issues/23.


Please try to use [the new 1.2.0 version](https://github.com/Markenson/csv-metabase-driver/releases/download/1.2.0/csv.metabase-driver.jar).

Just now I tried with https://raw.githubusercontent.com/Markenson/csv-metabase-driver/master/samples/ URL and works fine.

**Comment by Markenson** [comment]
Hi @ericknudson !

I think you had success. If don't, please inform.

Regards!
